In [2]:
import json
import pandas as pd
import numpy as np

In [3]:
# with open("YT-dataset-new/US_category_id.json") as f:
#     categories = json.load(f)["items"]
    
# cat_dict = {}
# for cat in categories:
#     cat_dict[int(cat["id"])] = cat["snippet"]["title"]

In [4]:
# cat_dict

In [59]:
df = pd.read_csv('US_youtube_trending_data_sentiment.csv')

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 151092 entries, 0 to 151091
Data columns (total 24 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Unnamed: 0           151092 non-null  int64
 1   Unnamed: 0.1         151092 non-null  int64
 2   video_id             151092 non-null  object
 3   title                151092 non-null  object
 4   publishedAt          151092 non-null  object
 5   channelId            151092 non-null  object
 6   channelTitle         151092 non-null  object
 7   categoryId           151092 non-null  int64
 8   trending_date        151092 non-null  object
 9   tags                 151092 non-null  object
 10  view_count           151092 non-null  int64
 11  likes                151092 non-null  int64
 12  dislikes             151092 non-null  int64
 13  comment_count        151092 non-null  int64
 14  thumbnail_link       151092 non-null  object
 15  comments_disabled    151092 non-null  bool
 16  ratings_disabled     151092 non-null  bool
 17  description          151092 non-null  object
 18  category             151092 non-null  object
 19  days_to_trend        151092 non-null  int64
 20  Cleaned Description  150824 non-null  object
 21  Sentiment_Scores     151092 non-null  float64
 22  Sentiment_Category   151092 non-null  object
 23  popularity           151092 non-null  bool
dtypes: bool(3), float64(1), int64(8), object(12)
memory usage: 24.6+ MB

In [7]:
# df['category'] = df['categoryId'].map(cat_dict)

In [8]:
df['category'].value_counts()

Entertainment            30024
Gaming                   29828
Music                    25497
Sports                   16116
People & Blogs           12817
Comedy                    7909
Film & Animation          6066
News & Politics           5815
Science & Technology      4773
Howto & Style             4428
Education                 3565
Autos & Vehicles          2722
Travel & Events            737
Pets & Animals             683
Nonprofits & Activism      112
Name: category, dtype: int64

In [9]:
# df.to_csv('US_youtube_trending_data.csv')

In [10]:
# from datetime import datetime

# def __datetime(date_str):
#     return datetime.strptime(date_str, "%Y-%m-%dT%H:%M:%SZ")

In [11]:
# df['days_to_trend'] = 0
# for i in range(len(df)):
#     df['days_to_trend'][i] = (__datetime(df['trending_date'][i]) - __datetime(df['publishedAt'][i])).days

In [12]:
# df['days_to_trend'].value_counts()

In [13]:
# df.head()

In [14]:
# df.drop(df[df.days_to_trend == -1].index, inplace = True)

In [60]:
dfTest = df
dfTest.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 151092 entries, 0 to 151091
Data columns (total 22 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Unnamed: 0           151092 non-null  int64
 1   video_id             151092 non-null  object
 2   title                151092 non-null  object
 3   publishedAt          151092 non-null  object
 4   channelId            151092 non-null  object
 5   channelTitle         151092 non-null  object
 6   categoryId           151092 non-null  int64
 7   trending_date        151092 non-null  object
 8   tags                 151092 non-null  object
 9   view_count           151092 non-null  int64
 10  likes                151092 non-null  int64
 11  dislikes             151092 non-null  int64
 12  comment_count        151092 non-null  int64
 13  thumbnail_link       151092 non-null  object
 14  comments_disabled    151092 non-null  bool
 15  ratings_disabled     151092 non-null  bool
 16  description          151092 non-null  object
 17  category             151092 non-null  object
 18  days_to_trend        151092 non-null  int64
 19  Cleaned Description  150824 non-null  object
 20  Sentiment Scores     151092 non-null  float64
 21  Sentiment Category   151092 non-null  object
dtypes: bool(2), float64(1), int64(7), object(12)
memory usage: 23.3+ MB

In [61]:
dfTest.head()

,Unnamed: 0,video_id,title,publishedAt,channelId,channelTitle,categoryId,trending_date,tags,view_count,...,comment_count,thumbnail_link,comments_disabled,ratings_disabled,description,category,days_to_trend,Cleaned Description,Sentiment Scores,Sentiment Category
0,0,3C66w5Z0ixs,I ASKED HER TO BE MY GIRLFRIEND...,2020-08-11T19:20:14Z,UCvtRTOMP2TqYqu51xNrqAzg,Brawadis,22,2020-08-12T00:00:00Z,brawadis|prank|basketball|skits|ghost|funny vi...,1514614,...,35313,https://i.ytimg.com/vi/3C66w5Z0ixs/default.jpg,False,False,SUBSCRIBE to BRAWADIS â–¶ http://bit.ly/Subscrib...,People & Blogs,0,to BRAWADIS FOLLOW ME ON SOCIAL Snapchat b...,0.5371,Positive
1,1,M9Pmf9AB4Mo,Apex Legends | Stories from the Outlands â€“ â€œTh...,2020-08-11T17:00:10Z,UC0ZV6M2THA81QT9hrVWJG3A,Apex Legends,20,2020-08-12T00:00:00Z,Apex Legends|Apex Legends characters|new Apex ...,2381688,...,16549,https://i.ytimg.com/vi/M9Pmf9AB4Mo/default.jpg,False,False,"While running her own modding shop, Ramya Pare...",Gaming,0,While running her own modding shop Ramya Parek...,0.8625,Positive
2,2,J78aPJ3VyNs,I left youtube for a month and THIS is what ha...,2020-08-11T16:34:06Z,UCYzPXprvl5Y-Sf0g4vX-m6g,jacksepticeye,24,2020-08-12T00:00:00Z,jacksepticeye|funny|funny meme|memes|jacksepti...,2038853,...,40221,https://i.ytimg.com/vi/J78aPJ3VyNs/default.jpg,False,False,I left youtube for a month and this is what ha...,Entertainment,0,I left for a month and this is what happenedMY...,0.5574,Positive
3,3,kXLn3HkpjaA,XXL 2020 Freshman Class Revealed - Official An...,2020-08-11T16:38:55Z,UCbg_UMjlHJg_19SZckaKajg,XXL,10,2020-08-12T00:00:00Z,xxl freshman|xxl freshmen|2020 xxl freshman|20...,496771,...,7647,https://i.ytimg.com/vi/kXLn3HkpjaA/default.jpg,False,False,Subscribe to XXL â†’ http://bit.ly/subscribe-xxl...,Music,0,to XXL XXL presents the 2020 XXL Freshman Cla...,0.7003,Positive
4,4,VIUo6yapDbc,Ultimate DIY Home Movie Theater for The LaBran...,2020-08-11T15:10:05Z,UCDVPcEbVLQgLZX0Rt6jo34A,Mr. Kate,26,2020-08-12T00:00:00Z,The LaBrant Family|DIY|Interior Design|Makeove...,1123889,...,2196,https://i.ytimg.com/vi/VIUo6yapDbc/default.jpg,False,False,Transforming The LaBrant Family's empty white ...,Howto & Style,0,Transforming The LaBrant Familys empty white r...,0.7650,Positive

In [62]:
mean_view = dfTest['view_count'].median()
mean_comment = dfTest['comment_count'].median()
mean_votes = (dfTest['likes'] + dfTest['dislikes']).median()

In [63]:
print(mean_view, mean_comment, mean_votes)

1011647.0 3222.0 46660.0

In [65]:
dfTest['popularity'] = np.where((dfTest['view_count'] > mean_view) & (dfTest['comment_count'] > mean_comment) & ((dfTest['likes'] + dfTest['dislikes']) > mean_votes), True, False)

In [66]:
dfTest.head()

,Unnamed: 0,video_id,title,publishedAt,channelId,channelTitle,categoryId,trending_date,tags,view_count,...,thumbnail_link,comments_disabled,ratings_disabled,description,category,days_to_trend,Cleaned Description,Sentiment Scores,Sentiment Category,popularity
0,0,3C66w5Z0ixs,I ASKED HER TO BE MY GIRLFRIEND...,2020-08-11T19:20:14Z,UCvtRTOMP2TqYqu51xNrqAzg,Brawadis,22,2020-08-12T00:00:00Z,brawadis|prank|basketball|skits|ghost|funny vi...,1514614,...,https://i.ytimg.com/vi/3C66w5Z0ixs/default.jpg,False,False,SUBSCRIBE to BRAWADIS â–¶ http://bit.ly/Subscrib...,People & Blogs,0,to BRAWADIS FOLLOW ME ON SOCIAL Snapchat b...,0.5371,Positive,True
1,1,M9Pmf9AB4Mo,Apex Legends | Stories from the Outlands â€“ â€œTh...,2020-08-11T17:00:10Z,UC0ZV6M2THA81QT9hrVWJG3A,Apex Legends,20,2020-08-12T00:00:00Z,Apex Legends|Apex Legends characters|new Apex ...,2381688,...,https://i.ytimg.com/vi/M9Pmf9AB4Mo/default.jpg,False,False,"While running her own modding shop, Ramya Pare...",Gaming,0,While running her own modding shop Ramya Parek...,0.8625,Positive,True
2,2,J78aPJ3VyNs,I left youtube for a month and THIS is what ha...,2020-08-11T16:34:06Z,UCYzPXprvl5Y-Sf0g4vX-m6g,jacksepticeye,24,2020-08-12T00:00:00Z,jacksepticeye|funny|funny meme|memes|jacksepti...,2038853,...,https://i.ytimg.com/vi/J78aPJ3VyNs/default.jpg,False,False,I left youtube for a month and this is what ha...,Entertainment,0,I left for a month and this is what happenedMY...,0.5574,Positive,True
3,3,kXLn3HkpjaA,XXL 2020 Freshman Class Revealed - Official An...,2020-08-11T16:38:55Z,UCbg_UMjlHJg_19SZckaKajg,XXL,10,2020-08-12T00:00:00Z,xxl freshman|xxl freshmen|2020 xxl freshman|20...,496771,...,https://i.ytimg.com/vi/kXLn3HkpjaA/default.jpg,False,False,Subscribe to XXL â†’ http://bit.ly/subscribe-xxl...,Music,0,to XXL XXL presents the 2020 XXL Freshman Cla...,0.7003,Positive,False
4,4,VIUo6yapDbc,Ultimate DIY Home Movie Theater for The LaBran...,2020-08-11T15:10:05Z,UCDVPcEbVLQgLZX0Rt6jo34A,Mr. Kate,26,2020-08-12T00:00:00Z,The LaBrant Family|DIY|Interior Design|Makeove...,1123889,...,https://i.ytimg.com/vi/VIUo6yapDbc/default.jpg,False,False,Transforming The LaBrant Family's empty white ...,Howto & Style,0,Transforming The LaBrant Familys empty white r...,0.7650,Positive,False

In [67]:
dfTest.to_csv('US_youtube_trending_data_popularity.csv', index=False)

In [34]:
df = pd.read_csv('US_youtube_trending_data_popularity.csv')

In [35]:
df = df[['publishedAt','Sentiment_Scores']]

In [41]:
# df['publishedAt'] = df['publishedAt'][:][:10]
df

       publishedAt  Sentiment_Scores
0       2020-08-11            0.5371
1       2020-08-11            0.8625
2       2020-08-11            0.5574
3       2020-08-11            0.7003
4       2020-08-11            0.7650
...            ...               ...
151087  2022-09-20            0.7946
151088  2022-09-21            0.0516
151089  2022-09-20           -0.6808
151090  2022-09-19            0.0000
151091  2022-09-20            0.8964

[151092 rows x 2 columns]

In [37]:
for i, row in df.iterrows():
    df.at[i,'publishedAt'] = df[i]

C:\Users\nirma\anaconda3\envs\infoviz\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [43]:
df.to_csv('US_youtube_trending_data_calendar.csv')

In [47]:
df = pd.read_csv('US_youtube_trending_data_calendar.csv')

In [49]:
df = df[['publishedAt', 'Sentiment_Scores']]

In [50]:
df

       publishedAt  Sentiment_Scores
0       2020-08-11            0.5371
1       2020-08-11            0.8625
2       2020-08-11            0.5574
3       2020-08-11            0.7003
4       2020-08-11            0.7650
...            ...               ...
151087  2022-09-20            0.7946
151088  2022-09-21            0.0516
151089  2022-09-20           -0.6808
151090  2022-09-19            0.0000
151091  2022-09-20            0.8964

[151092 rows x 2 columns]

In [53]:
df.to_csv('US_youtube_trending_data_calendar.csv', index=False)

In [52]:
df

       publishedAt  Sentiment_Scores
0       2020-08-11            0.5371
1       2020-08-11            0.8625
2       2020-08-11            0.5574
3       2020-08-11            0.7003
4       2020-08-11            0.7650
...            ...               ...
151087  2022-09-20            0.7946
151088  2022-09-21            0.0516
151089  2022-09-20           -0.6808
151090  2022-09-19            0.0000
151091  2022-09-20            0.8964

[151092 rows x 2 columns]